#!/usr/bin/env ruby

# To debug without installing, run as `ruby -I lib exe/tool...`
require "jade_systems_toolbox"

begin
  JadeSystemsToolbox::Cli.start(ARGV)
rescue StandardError => exception
  JadeSystemsToolbox::ErrorReporter.report(exception)
  exit(1)
end
